import 'package:websitepesan/model/makanan.dart';
import 'package:websitepesan/model/minuman.dart';
import 'package:websitepesan/model/produk.dart';

class DummyData {
  static List<Produk> getProdukList() {
    return [
      Makanan(
        id: '1',
        nama: 'Mie Gacoan Original',
        deskripsi: 'Mie goreng dengan bumbu spesial khas Gacoan, disajikan dengan topping ayam, udang, dan sayuran segar.',
        harga: 15000,
        gambar: 'assets/mie gacoan.jpg',
        rating: 4.8,
        pedas: true,
        kategori: 'Mie',
      ),
      Makanan(
        id: '2',
        nama: 'Mie Gacoan Keju',
        deskripsi: 'Mie goreng dengan tambahan keju mozarella yang melimpah, cocok untuk pecinta keju.',
        harga: 20000,
        gambar: 'assets/unesa logo.png',
        rating: 4.7,
        pedas: false,
        kategori: 'Mie',
      ),
      Minuman(
        id: '3',
        nama: 'Es Teh Manis',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/unesa logo.png',
        rating: 4.5,
        dingin: true,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '4',
        nama: 'Jus Alpukat',
        deskripsi: 'Jus alpukat segar dengan susu kental manis dan es serut, memberikan sensasi creamy yang nikmat.',
        harga: 12000,
        gambar: 'assets/unesa logo.png',
        rating: 4.9,
        dingin: true,
        ukuran: 'Besar',
      ),
      Makanan(
        id: '5',
        nama: 'Pangsit Goreng',
        deskripsi: 'Pangsit goreng renyah dengan isian ayam dan udang, disajikan dengan saus spesial.',
        harga: 10000,
        gambar: 'assets/unesa logo.png',
        rating: 4.6,
        pedas: false,
        kategori: 'Appetizer',
      ),
      Makanan(
        id: '5',
        nama: 'Pangsit Goreng',
        deskripsi: 'Pangsit goreng renyah dengan isian ayam dan udang, disajikan dengan saus spesial.',
        harga: 10000,
        gambar: 'assets/unesa logo.png',
        rating: 4.6,
        pedas: false,
        kategori: 'Appetizer',
      ),
      Makanan(
        id: '5',
        nama: 'Pangsit Goreng',
        deskripsi: 'Pangsit goreng renyah dengan isian ayam dan udang, disajikan dengan saus spesial.',
        harga: 10000,
        gambar: 'assets/unesa logo.png',
        rating: 4.6,
        pedas: false,
        kategori: 'Appetizer',
      ),
      Makanan(
        id: '5',
        nama: 'Pangsit Goreng',
        deskripsi: 'Pangsit goreng renyah dengan isian ayam dan udang, disajikan dengan saus spesial.',
        harga: 10000,
        gambar: 'assets/unesa logo.png',
        rating: 4.6,
        pedas: false,
        kategori: 'Appetizer',
      ),
      Makanan(
        id: '5',
        nama: 'Pangsit Goreng',
        deskripsi: 'Pangsit goreng renyah dengan isian ayam dan udang, disajikan dengan saus spesial.',
        harga: 10000,
        gambar: 'assets/unesa logo.png',
        rating: 4.6,
        pedas: false,
        kategori: 'Appetizer',
      ),
      Makanan(
        id: '6',
        nama: 'Sate Ayam',
        deskripsi: 'Sate ayam dengan bumbu kacang yang khas, disajikan dengan lontong dan bawang goreng.',
        harga: 18000,
        gambar: 'assets/unesa logo.png',
        rating: 4.7,
        pedas: true,
        kategori: 'Appetizer',
      ),
      Minuman(
        id: '3',
        nama: 'Es Teh Manis',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/unesa logo.png',
        rating: 4.5,
        dingin: true,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '4',
        nama: 'Jus Alpukat',
        deskripsi: 'Jus alpukat segar dengan susu kental manis dan es serut, memberikan sensasi creamy yang nikmat.',
        harga: 12000,
        gambar: 'assets/unesa logo.png',
        rating: 4.9,
        dingin: true,
        ukuran: 'Besar',
      ),
      Minuman(
        id: '3',
        nama: 'Es Teh Manis',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/unesa logo.png',
        rating: 4.5,
        dingin: true,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '4',
        nama: 'Jus Alpukat',
        deskripsi: 'Jus alpukat segar dengan susu kental manis dan es serut, memberikan sensasi creamy yang nikmat.',
        harga: 12000,
        gambar: 'assets/unesa logo.png',
        rating: 4.9,
        dingin: true,
        ukuran: 'Besar',
      ),
      Minuman(
        id: '3',
        nama: 'Es Teh Manis',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/unesa logo.png',
        rating: 4.5,
        dingin: true,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '4',
        nama: 'Jus Alpukat',
        deskripsi: 'Jus alpukat segar dengan susu kental manis dan es serut, memberikan sensasi creamy yang nikmat.',
        harga: 12000,
        gambar: 'assets/unesa logo.png',
        rating: 4.9,
        dingin: true,
        ukuran: 'Besar',
      ),
      Minuman(
        id: '3',
        nama: 'Es Teh Manis',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/unesa logo.png',
        rating: 4.5,
        dingin: true,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '4',
        nama: 'Jus Alpukat',
        deskripsi: 'Jus alpukat segar dengan susu kental manis dan es serut, memberikan sensasi creamy yang nikmat.',
        harga: 12000,
        gambar: 'assets/unesa logo.png',
        rating: 4.9,
        dingin: true,
        ukuran: 'Besar',
      ),
    ];
  }
}
